app:
  name: "web_reddit"
  mode: "dev"
  port: 8081
log:
  level: "debug"
  filename: "web_reddit.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "192.168.149.133"
  port: 3306
  user: root
  password: "123456"
  dbname: "sql_demo"
  max_open: 200
  idle: 10
redis:
  host: "192.168.149.133"
  port: 6379
  db: 0
  password: ""
  pool_size: 100